# See https://docs.rubocop.org/rubocop/configuration

require:
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable

Style/Documentation:
  Enabled: false

RSpec/ExampleLength:
  Exclude: 
    - spec/views/**/*

RSpec/NestedGroups:
  Max: 5

RSpec/MultipleExpectations:
  Exclude: 
    - spec/views/**/*

RSpec/MultipleMemoizedHelpers:
  Max: 7
