default: &default
  adapter: sqlite3
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS', 5) %>
  # username: <%= ENV.fetch('DB_USER', 'postgres') %>
  # password: <%= ENV.fetch('DB_PASS', 'sekret') %>
  # host: <%= ENV.fetch('DB_HOST', 'localhost') %>

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  database: db/test.sqlite3

production:
  <<: *default
  database: db/production.sqlite3
  # username: schola
  # password: <%= ENV["SCHOLA_DATABASE_PASSWORD"] %>
